"use client";

import styles from "@/styles/layout.module.css";
import { ProtectedLayout, FaqsTable, FaqsModalCard } from "@/components";
import Link from "next/link";
import { useDispatch, useSelector } from "react-redux";
import { setFaqFormActive } from "@/redux/services/sitemap/sitemapSlice";

// export const metadata = {
//   title: "Frequently Asked Questions",
//   description: "Generated by create next app",
// };

const FaqsAdminPage = () => {
  const dispatch = useDispatch();
  const { FaqForm } = useSelector((state) => state.sitemap);

  const handleNewFaq = () => {
    dispatch(setFaqFormActive());
  };

  return (
    <ProtectedLayout>
      <div className="row">
        <div className="col-lg-12 col-md-12 col-sm-12">
          <div className={`card ${styles.card}`}>
            <div
              className={`${styles.page_header} d-flex flex-column flex-wrap`}
            >
              <div className="d-flex justify-content-between flex-lg-row">
                <h4>Frequently Asked Questions</h4>
                <span
                  className={styles.page_header_btn}
                  onClick={() => handleNewFaq()}
                >
                  Create New
                </span>
              </div>

              <p>
                This is your contact database. From here, you can view, organize
                and manage your contacts, individually or as a group.
              </p>
            </div>
            <div className="card-body">
              <FaqsTable />
            </div>
          </div>
        </div>
      </div>
      {FaqForm && <FaqsModalCard />}
    </ProtectedLayout>
  );
};

export default FaqsAdminPage;
