import styles from "@/styles/layout.module.css";
import { ProtectedLayout, ContactUsTable, QuotationTable } from "@/components";

export const metadata = {
  title: "Services Quotation",
  description: "Generated by create next app",
};

const ServiceQuotationPage = () => {
  return (
    <ProtectedLayout>
      <div className="row">
        <div className="col-lg-12 col-md-12 col-sm-12">
          <div className={`card ${styles.card}`}>
            <div
              className={`${styles.page_header} d-flex flex-column flex-wrap`}
            >
              <h4>Services Form Quotation</h4>
              <p>
                This is your contact database. From here, you can view, organize
                and manage your contacts, individually or as a group.
              </p>
            </div>
            <div className="card-body">
              <QuotationTable />
            </div>
          </div>
        </div>
      </div>
    </ProtectedLayout>
  );
};

export default ServiceQuotationPage;
