import styles from "@/styles/faqs.module.css";
import { MainLayout, FaqsCard } from "@/components";

export const metadata = {
  title: "Frequently Asked Questions",
  description: "Generated by create next app",
};

const FaqsPage = () => {
  return (
    <MainLayout>
      <section className="w-100 h-100 position-relative">
        <div className={styles.faqs_banner}>
          <div className="container-fluid nav_padding">
            <div className="row ">
              <div className="col-lg-6 col-md-12 col-sm-12">
                <h2>Frequently Asked Questions</h2>
                <p>
                  We would love to collaborate with your organization. Please
                  share some information about yourself and we will immediately
                  get in touch with you.
                </p>
              </div>
            </div>
          </div>
        </div>
        <FaqsCard />
      </section>
    </MainLayout>
  );
};

export default FaqsPage;
