import {
  MainLayout,
  FaqsCard,
  CustomBannerCard,
  TestimonialsCard,
} from "@/components";

export const metadata = {
  title: "Frequently Asked Questions",
  description: "Generated by create next app",
};

const FaqsPage = () => {
  return (
    <MainLayout>
      <section className="w-100 h-100 position-relative">
        <CustomBannerCard
          title="Frequently Asked Questions"
          description="We would love to collaborate with your organization. Please
          share some information about yourself and we will immediately
          get in touch with you."
        />
        <FaqsCard />
        <TestimonialsCard />
      </section>
    </MainLayout>
  );
};

export default FaqsPage;
