// import styles from "../page.module.css";
import {
  HeroBannerSlider,
  HomeAboutUsCard,
  HomeMissionVisionCard,
  MainLayout,
  ServicesCard,
  TestimonialsCard,
} from "@/components";

export const metadata = {
  title: "Welcome | Adla Investment Enterprises",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <MainLayout>
      <section className="banner-container w-100 h-100 position-relative">
        <div className="position-relative h-100">
          <HeroBannerSlider />
          {/* <div className={styles.banner_divider} /> */}
          <HomeAboutUsCard />
          <ServicesCard />
          <HomeMissionVisionCard />
          <TestimonialsCard />
        </div>
      </section>
    </MainLayout>
  );
}
