"use client";

import "./globals.css";
import { DM_Sans } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import { Navbar, Footer, Loading } from "@/components";
import dynamic from "next/dynamic";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import NextProgress from "next-progress";
import { ToastContainer } from "react-toastify";

const DMSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const DynamicBootstrap = dynamic(
  () => require("bootstrap/dist/js/bootstrap.min.js"),
  { ssr: false }
);

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={DMSans.className}>
          <main className="overflow-hidden">
            <Navbar />
            <ToastContainer autoClose={2500} />
            <NextProgress
              color="#fba543"
              height="3px"
              delay={400}
              options={{ showSpinner: true }}
            />
            {children}
            <Footer />
          </main>
        </body>
      </html>
    </Provider>
  );
}
