import "./globals.css";
// import localFont from "next/font/local";
import { DM_Sans } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import { Navbar, Footer, Loading } from "@/components";
import dynamic from "next/dynamic";

// const quasimoda = localFont({
//   src: [
//     {
//       path: "../public/static/fonts/quasimoda_medium.ttf",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../public/static/fonts/quasimoda_light.otf",
//       weight: "700",
//       style: "normal",
//     },
//   ],
// });

const DMSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DynamicBootstrap = dynamic(
  () => require("bootstrap/dist/js/bootstrap.min.js"),
  { ssr: false }
);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={DMSans.className}>
        <main className="overflow-hidden">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
