import styles from "@/styles/layout.module.css";
import { ProtectedLayout, PasswordConfig, WebsiteConfig } from "@/components";
// import { SiteConfigurationForm, ChangePasswordForm } from "@/components/Forms";

export const metadata = {
  title: "Configurations",
  description: "Generated by create next app",
};

const WebsiteConfigPage = () => {
  return (
    <ProtectedLayout>
      <div className="row">
        <WebsiteConfig />
        <PasswordConfig />

        {/* <div className="col-lg-12 col-md-12 col-sm-12">
          <div className={`card ${styles.card}`}>
            <div
              className={`${styles.page_header} d-flex flex-column flex-wrap`}
            >
              <h4>Website Confirgurations</h4>
              <p>
                This is your contact database. From here, you can view, organize
                and manage your contacts, individually or as a group.
              </p>
            </div>
            <div className={`card-body ${styles.card_body} p-0`}>
              <SiteConfigurationForm />
            </div>
          </div>
        </div> */}

        {/* <div className="col-lg-12 col-md-12 col-sm-12">
          <div className={`card ${styles.card}`}>
            <div
              className={`${styles.page_header} d-flex flex-column flex-wrap`}
            >
              <h4>Change Password</h4>
              <p>
                This is your contact database. From here, you can view, organize
                and manage your contacts, individually or as a group.
              </p>
            </div>
          

            <div className={`card-body ${styles.card_body} p-0`}>
              <ChangePasswordForm />
            </div>
          </div>
        </div> */}
      </div>
    </ProtectedLayout>
  );
};

export default WebsiteConfigPage;
