import styles from "@/styles/layout.module.css";
import Image from "next/image";
import { LoginForm } from "@/components/Forms";

export const metadata = {
  title: "Service Inquiry | Get Quote",
  description: "Generated by create next app",
};

const LoginPage = () => {
  return (
    <main className="overflow-hidden">
      <div className="container-fluid px-0">
        <div className="d-flex w-100 position-relative vh-100">
          <div className={styles.auth_ltr_bg} />
          <div className={`${styles.auth_rtl_container} flex-column d-flex`}>
            <div className={styles.auth_logo} />
            
            <div
              className={`${styles.auth_form} w-100 d-flex align-items-lg-center justify-content-lg-start flex-lg-column`}
            >
              <h4>Welcome Back!</h4>
              <LoginForm />
            </div>
          </div>
        </div>
      </div>
    </main>
  );
};

export default LoginPage;
