import {
  MainLayout,
  CustomBannerCard,
  ServicesCard,
  WhoWeAreCard,
  TestimonialsCard,
  MissionVisionCard,
} from "@/components";

export const metadata = {
  title: "About Adla Global Business",
  description: "Generated by create next app",
};
const AboutUsPage = () => {
  return (
    <MainLayout>
      <section className="w-100 h-100 position-relative">
        <CustomBannerCard
          title="About Us"
          description="At Adla Global Investment, we boast an extensive service portfolio that centers around fulfilling our clients' purchasing demands by sourcing products both locally and internationally. Our African-based clientele can rest easy knowing that we provide all the necessary export documentation, product cost, transport, freight insurance, and more."
        />
        <WhoWeAreCard />
        <MissionVisionCard />
        <ServicesCard />
        <TestimonialsCard />
      </section>
    </MainLayout>
  );
};

export default AboutUsPage;
