import {
  MainLayout,
  CustomBannerCard,
  ServicesCard,
  WhoWeAreCard,
  TestimonialsCard,
  MissionVisionCard,
} from "@/components";

export const metadata = {
  title: "About Adla Global Business",
  description: "Generated by create next app",
};
const AboutUsPage = () => {
  return (
    <MainLayout>
      <section className="w-100 h-100 position-relative">
        <CustomBannerCard
          title="About Us"
          description=" Lorem iosum dolor sit amet. consectetur adiviscina elit. sed
          do eiusmod tempor incididunt ut labore et dolore magna.
          Lorem iosum dolor sit amet. consectetur adiviscina elit. sed
          do eiusmod tempor incididunt ut labore et dolore magna."
        />
        <WhoWeAreCard />
        <MissionVisionCard />
        <ServicesCard />
        <TestimonialsCard />
      </section>
    </MainLayout>
  );
};

export default AboutUsPage;
