// "use client";

import styles from "@/styles/about.module.css";
import { ImQuotesLeft } from "react-icons/im";
import {
  MainLayout,
  ServicesCard,
  WhoWeAreCard,
  FaqsCard,
  TestimonialsCard,
} from "@/components";

export const metadata = {
  title: "About Adla",
  description: "Generated by create next app",
};
const AboutUsPage = () => {
  return (
    <MainLayout>
      <section className="w-100 h-100 position-relative">
        <div className={styles.about_us_banner}>
          <div className="container-fluid nav_padding">
            <div className="row ">
              <div className="col-lg-6 col-md-12 col-sm-12">
                <div className={styles.contact_us_title}>
                  <h2>About Us</h2>
                  <p>
                    Lorem iosum dolor sit amet. consectetur adiviscina elit. sed
                    do eiusmod tempor incididunt ut labore et dolore magna.
                    Lorem iosum dolor sit amet. consectetur adiviscina elit. sed
                    do eiusmod tempor incididunt ut labore et dolore magna.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-pattern" />
        <WhoWeAreCard />

        {/* <div className={styles.about_us}>
          <div className="container-fluid nav_padding">
            <div className="row">
              <div className="col-lg-6 col-md-12 col-sm-12">
              <span className={styles.about_us_badge}>Who we are</span>
                <h4>
                  Benefit from our industry expertise, dependable sourcing,
                  efficient logistics, and customer-focused approach.
                </h4>
                <p className="pt-lg-2">
                  We work with carefully selected suppliers that meet our
                  quality control standards in order to reduce the possibility
                  of contamination. The elaborate processes that we undertake
                  assure clients of our unwavering commitment to delivering high
                  quality products. Our products can be packed according to the
                  buyers’ custom requirements. Additionally, we deliver all
                  shipments promptly as required. We work with carefully
                  selected suppliers that meet our quality control standards in
                  order to reduce the possibility of contamination.
                </p>
                <p className="py-lg-4">
                  We work with carefully selected suppliers that meet our
                  quality control standards in order to reduce the possibility
                  of contamination. The elaborate processes that we undertake
                  assure clients of our unwavering commitment to delivering high
                  quality products. Our products can be packed according to the
                  buyers’ custom requirements. The elaborate processes that we
                  undertake assure clients of our unwavering commitment to
                  delivering high quality products. Our products can be packed
                  according to the buyers’ custom requirements. Additionally, we
                  deliver all shipments promptly as required.
                </p>
              </div>
              <div className="col-lg-6 col-md-12 col-sm-12">
                <div className={styles.about_us_rtl_img_01} />
                <div className={styles.about_us_rtl_quote_card}>
                  <ImQuotesLeft size={80} />

                  <p>
                    We offer customized solutions to fulfill your sourcing
                    requirements and make global trade smoother with our vast
                    experience and network.
                  </p>
                  <div></div>
                </div>
              </div>
            </div>
          </div>
        </div> */}
        <div className={`${styles.vision_mission_section} position-relative`}>
          <div className="container-fluid nav_padding">
            <div className="row">
              <div
                className={`${styles.vision_mission_content} col-lg-10 offset-lg-1 col-md-12 col-sm-12`}
              >
                <div className={styles.vision_mission_text_container}>
                  <h4>
                    We specialize in sourcing the finest agro commodities, base
                    metal and minor metals.
                  </h4>
                </div>

                <div className={styles.vision_mission_container}>
                  <div className="row">
                    <div className="col-lg-4 col-md-6 col-sm-12">
                      {/* <div className={styles.mission_top_wrapper}>
                        <span />
                      </div> */}

                      <div
                        className={`${styles.mission_bottom_wrapper} d-flex justify-content-center align-items-center flex-column`}
                      >
                        <span className={styles.mission_icon} />
                        <h4>Our Mission</h4>
                        <p>
                          Equal blame belongs to those who fail in their duty
                          through weakness of will which the same as saying.{" "}
                        </p>
                      </div>
                    </div>
                    <div className="col-lg-4 col-md-6 col-sm-12">
                      <div
                        className={`${styles.core_values_wrapper} d-flex justify-content-center align-items-center flex-column`}
                      >
                        <span className={styles.values_icon} />
                        <h4>Our Core Values</h4>
                        <p>
                          Our approach involves accountability, responsiveness,
                          honesty, and collaboration as we provide
                          problem-solving solutions for companies and talents
                          worldwide.
                        </p>
                      </div>

                      {/* <div
                        className={`${styles.core_values_wrapper} d-flex justify-content-center align-items-center flex-column`}
                      >
                        <span className={styles.vision_icon} />
                        <h4>Our Vision</h4>
                        <p>
                          We aspire to become the leading provider and
                          distributor of spices and organic poultry in Africa,
                          both in terms of production and exportation.
                        </p>
                      </div> */}
                    </div>

                    <div className="col-lg-4 col-md-6 col-sm-12">
                      {/* <div
                        className={`${styles.core_values_wrapper} d-flex justify-content-center align-items-center flex-column`}
                      >
                        <span className={styles.values_icon} />
                        <h4>Our Core Values</h4>
                        <p>
                          Our approach involves accountability, responsiveness,
                          honesty, and collaboration as we provide
                          problem-solving solutions for companies and talents
                          worldwide.
                        </p>
                      </div> */}

                      <div
                        className={`${styles.core_values_wrapper} d-flex justify-content-center align-items-center flex-column`}
                      >
                        <span className={styles.vision_icon} />
                        <h4>Our Vision</h4>
                        <p>
                          We aspire to become the leading provider and
                          distributor of spices and organic poultry in Africa,
                          both in terms of production and exportation.
                        </p>
                      </div>
                    </div>
                    {/* <div className="col-lg-4 col-md-12 col-sm-12">
                      <div
                        className={styles.mission_vision_placeholder_wrapper}
                      >
                        <span />
                      </div>
                    </div> */}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <ServicesCard />
        <TestimonialsCard />
      </section>
    </MainLayout>
  );
};

export default AboutUsPage;
