import styles from "@/styles/layout.module.css";
import { ProtectedLayout, DashboardBarChart } from "@/components";


export const metadata = {
  title: "Administrator Dashboard",
  description: "Generated by create next app",
};

const DashboardPage = () => {
  return (
    <ProtectedLayout>
      <div className="row">
        <DashboardBarChart />
        <div className="col-lg-12 col-md-12 col-sm-12">
          <div className={`card ${styles.card}`}>
            <div
              className={`${styles.pageHeader} d-flex align-items-lg-center justify-content-lg-between flex-wrap`}
            >
              <h5>Notifications</h5>
            </div>
          </div>
        </div>
      </div>
    </ProtectedLayout>
  );
};

export default DashboardPage;
